training <- read.csv("train.csv")[,-c(17,15,2,3)]
train <- train[training$Fatal=="F" | training$Fatal=="N",]
test <- read.csv("test.csv")[,-c(17,15,2,3)]

# Cleaning Train for Nature of Stop
train$NatureOfStop <- gsub("^[sS]hooting.+", "Shots Fired", train$NatureOfStop)
train$NatureOfStop <- gsub("^[sS]hooting", "Shots Fired", train$NatureOfStop)
train$NatureOfStop <- gsub("^Accidental Discharge w/ injuries", "Shots Fired", train$NatureOfStop)
train$NatureOfStop <- gsub("^accidental shooting", "Shots Fired", train$NatureOfStop)
train$NatureOfStop <- gsub("^Domestic violence; shots fired", "Shots Fired", train$NatureOfStop)
train$NatureOfStop <- gsub("^Person shot", "Shots Fired", train$NatureOfStop)
train$NatureOfStop <- gsub("^Crowd-control; shooting", "Shots Fired", train$NatureOfStop)
train$NatureOfStop <- gsub("^Prostitution; police shooting", "Shots Fired", train$NatureOfStop)
train$NatureOfStop <- gsub("^Active shooter", "Shots Fired", train$NatureOfStop)
train$NatureOfStop <- gsub("^[sS]hots\\s[fF]ired.+", "Shots Fired", train$NatureOfStop)
train$NatureOfStop <- gsub("^Disturbance; crowd-control; gunshots", "Shots Fired", train$NatureOfStop)
train$NatureOfStop <- gsub("^[sS]hots\\s[fF]ired", "Shots Fired", train$NatureOfStop)
train$NatureOfStop <- gsub("^Assault on officer; shootings; gang", "Shots Fired", train$NatureOfStop)
train$NatureOfStop <- gsub("^Sound of Shots", "Shots Fired", train$NatureOfStop)
train$NatureOfStop <- gsub("^Fight; shots fired", "Shots Fired", train$NatureOfStop)
train$NatureOfStop <- gsub("^Sound of Shots", "Shots Fired", train$NatureOfStop)
train$NatureOfStop <- gsub("^[wW]eapon.+", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^[aA]rmed.+", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Drunkeness; weapons posession", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^[aA]rmed", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Assault; weapons posession; firearms", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Gun posession", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Gun possession", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Man with a gun", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("Person with a gun", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Party Armed", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^violent, armed dispute", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^weilding machete", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Party Armed-suicidal", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Disturbance; firearm", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Disturbance; firearms posession", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Weapon Possesion-suicidal", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Susp Party/Armed", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Domestic dispute; weapons posession; firearm", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Domestic disturbance; firearm; suicide", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Sus Party Armed", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Firearm", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Drunkeness; weapons posession ", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^Bulletin indicating victim had firearm", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("^[mM]urder.+", "Homicide", train$NatureOfStop)
train$NatureOfStop <- gsub("^[mM]urder", "Homicide", train$NatureOfStop)
train$NatureOfStop <- gsub("^[sS]tabbing", "Homicide", train$NatureOfStop)
train$NatureOfStop <- gsub("^[hH]omicide.+", "Homicide", train$NatureOfStop)
train$NatureOfStop <- gsub("^woman being stabbed", "Homicide", train$NatureOfStop)
train$NatureOfStop <- gsub("^Homocide.+", "Homicide", train$NatureOfStop)
train$NatureOfStop <- gsub("Capital murder", "Homicide", train$NatureOfStop)
train$NatureOfStop <- gsub("Unknown", NA, train$NatureOfStop)
train$NatureOfStop <- gsub("^Agg Assault/Op 100", "Aggrevated Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^Agg. Assault", "Aggrevated Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^Agg. Assualt", "Aggrevated Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^Aggraveted assault", "Aggrevated Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^Agg DV Assault", "Aggrevated Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^aggravated battery", "Aggrevated Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^[fF]igh.+", "Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^Assaulting officer", "Aggrevated Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^Nag-Assault", "Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^[dD]omestic [vV]iolence$", "Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^Battery", "Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^Ambush", "Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^Violence Reduction", "Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^Violent altercation", "Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^Assault; car accident", "Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^Volent dispute", "Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^Volent dispute ", "Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^Domestic aggrevated assault", "Aggrevated Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("Domestic assault and battery; mental illness", "Assault", train$NatureOfStop)
train$NatureOfStop <- gsub("^suspicious.+|^Suspicious.+", "Suspicious Entity", train$NatureOfStop)
train$NatureOfStop <- gsub("^Susp.\\s.+", "Suspicious Entity", train$NatureOfStop)
train$NatureOfStop <- gsub("\"suspicious person looking into vehicles in the area\"", "Suspicious Entity", train$NatureOfStop)
train$NatureOfStop <- gsub("Surveillance", "Suspicious Entity", train$NatureOfStop)
train$NatureOfStop <- gsub("^Wanted\\s.+", "Suspect", train$NatureOfStop)
train$NatureOfStop <- gsub("^Stakeout", "Suspect", train$NatureOfStop)
train$NatureOfStop <- gsub("^Disturbance wanted-PCS", "Suspect", train$NatureOfStop)
train$NatureOfStop <- gsub("^Felony Car check", "Suspect", train$NatureOfStop)
train$NatureOfStop <- gsub("^Pursuit", "Suspect", train$NatureOfStop)
train$NatureOfStop <- gsub("^Felony fugitive", "Suspect", train$NatureOfStop)
train$NatureOfStop <- gsub("^Suspe.+", "Suspect", train$NatureOfStop)
train$NatureOfStop <- gsub("^BO.+", "Suspect", train$NatureOfStop)
train$NatureOfStop <- gsub("^gang activity", "Suspect", train$NatureOfStop)
train$NatureOfStop <- gsub("^Gang activity; nightlife", "Suspect", train$NatureOfStop)
train$NatureOfStop <- gsub("^Gang; suspicious person", "Suspect", train$NatureOfStop)
train$NatureOfStop <- gsub("^Search for suspect in an aggravated robbery", "Suspect", train$NatureOfStop)
train$NatureOfStop <- gsub("^Fugitive; Immigration and customs enforcement", "Suspect", train$NatureOfStop)
train$NatureOfStop <- gsub("domestic argument", "Disturbance", train$NatureOfStop)
train$NatureOfStop <- gsub("^[dD]omestic [dD]ispute$", "Disturbance", train$NatureOfStop)
train$NatureOfStop <- gsub("^[dD]omestic [dD]isturbance$", "Disturbance", train$NatureOfStop)
train$NatureOfStop <- gsub("domestic distrurbance", "Disturbance", train$NatureOfStop)
train$NatureOfStop <- gsub("Altercation", "Disturbance", train$NatureOfStop)
train$NatureOfStop <- gsub("complaint", "Disturbance", train$NatureOfStop)
train$NatureOfStop <- gsub("Loud music disturbance", "Disturbance", train$NatureOfStop)
train$NatureOfStop <- gsub("Major disturbance", "Disturbance", train$NatureOfStop)
train$NatureOfStop <- gsub("^.+nted-PCS$", "Disturbance", train$NatureOfStop)
train$NatureOfStop <- gsub("domestic distrubance", "Disturbance", train$NatureOfStop)
train$NatureOfStop <- gsub("Noise Disturbance", "Disturbance", train$NatureOfStop)
train$NatureOfStop <- gsub("Disturbance; emergency", "Disturbance", train$NatureOfStop)
train$NatureOfStop <- gsub("Animal disturbance", "Disturbance", train$NatureOfStop)
train$NatureOfStop <- gsub("Party", "Disturbance", train$NatureOfStop)
train$NatureOfStop <- gsub("^[dD]rug.+", "Narcotics", train$NatureOfStop)
train$NatureOfStop <- gsub("^Narcotics", "Narcotics", train$NatureOfStop)
train$NatureOfStop <- gsub("^Narcotics.+", "Narcotics", train$NatureOfStop)
train$NatureOfStop <- gsub("^Stolen [cC]ar", "Larceny", train$NatureOfStop)
train$NatureOfStop <- gsub("^Larceny.+", "Larceny", train$NatureOfStop)
train$NatureOfStop <- gsub("^[sS]tolen [vV]ehicle", "Larceny", train$NatureOfStop)
train$NatureOfStop <- gsub("vehicle burglary" , "Larceny", train$NatureOfStop)
train$NatureOfStop <- gsub("Stolen police car" , "Larceny", train$NatureOfStop)
train$NatureOfStop <- gsub("Shoplifter" , "Larceny", train$NatureOfStop)
train$NatureOfStop <- gsub(".+shoplifting$" , "Larceny", train$NatureOfStop)
train$NatureOfStop <- gsub("^Shoplifting", "Larceny", train$NatureOfStop)
train$NatureOfStop <- gsub("^Stolen Property", "Larceny", train$NatureOfStop)
train$NatureOfStop <- gsub("^Theft", "Larceny", train$NatureOfStop)
train$NatureOfStop <- gsub("^Stolen Auto", "Larceny", train$NatureOfStop)
train$NatureOfStop <- gsub("^Believed stolen vehicle", "Larceny", train$NatureOfStop)
train$NatureOfStop <- gsub("^Carjacking; weapons posession", "Larceny", train$NatureOfStop)
train$NatureOfStop <- gsub("^[bB]urglary.+", "Burglary", train$NatureOfStop)
train$NatureOfStop <- gsub("^[bB]urglary", "Burglary", train$NatureOfStop)
train$NatureOfStop <- gsub("^Breaking and entering", "Burglary", train$NatureOfStop)
train$NatureOfStop <- gsub("^[hH]ome [iI]nvasion", "Burglary", train$NatureOfStop)
train$NatureOfStop <- gsub("^[rRob].+", "Robbery", train$NatureOfStop)
train$NatureOfStop <- gsub("^Aggravated assault; robbery", "Robbery", train$NatureOfStop)
train$NatureOfStop <- gsub("^[bB]ank\\s.+", "Robbery", train$NatureOfStop)
train$NatureOfStop <- gsub("^Investigation; robbery", "Robbery", train$NatureOfStop)
train$NatureOfStop <- gsub("^possible robbery", "Robbery", train$NatureOfStop)
train$NatureOfStop <- gsub("^Aggravated robbery", "Robbery", train$NatureOfStop)
train$NatureOfStop <- gsub(".+obbery Apprehension$", "Robbery", train$NatureOfStop)
train$NatureOfStop <- gsub("^.+[wW]arrant.+", "Warrant", train$NatureOfStop)
train$NatureOfStop <- gsub("^[wW]arrant.+", "Warrant", train$NatureOfStop)
train$NatureOfStop <- gsub("^.+[wW]arrant", "Warrant", train$NatureOfStop)
train$NatureOfStop <- gsub("^[wW]arrant", "Warrant", train$NatureOfStop)
train$NatureOfStop <- gsub("^[wW]arrants", "Warrant", train$NatureOfStop)
train$NatureOfStop <- gsub("^[mM]enta.+", "Mental Health", train$NatureOfStop)
train$NatureOfStop <- gsub("^[sS]uici.+", "Mental Health", train$NatureOfStop)
train$NatureOfStop <- gsub("^Cutting", "Mental Health", train$NatureOfStop)
train$NatureOfStop <- gsub("^Disturbance; mental illness", "Mental Health", train$NatureOfStop)
train$NatureOfStop <- gsub("^Welfare\\s.+", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^emotionally disturbed person call", "Mental Health", train$NatureOfStop)
train$NatureOfStop <- gsub("^[cC]ar\\s.+", "Car Related", train$NatureOfStop)
train$NatureOfStop <- gsub("hit-and-run", "Crime", train$NatureOfStop)
train$NatureOfStop <- gsub("hit and run chase", "Crime", train$NatureOfStop)
train$NatureOfStop <- gsub("Fleeing vehicle", "Suspect", train$NatureOfStop)
train$NatureOfStop <- gsub("^[tT]raffic.+", "Car Related", train$NatureOfStop)
train$NatureOfStop <- gsub("^Hit and run", "Crime", train$NatureOfStop)
train$NatureOfStop <- gsub("^[vV]ehicle\\s.+", "Car Related", train$NatureOfStop)
train$NatureOfStop <- gsub("^D.U.I. Check Point", "Car Related", train$NatureOfStop)
train$NatureOfStop <- gsub("^Arson; traffic stop", "Car Related", train$NatureOfStop)
train$NatureOfStop <- gsub("^Police chase", "Suspect", train$NatureOfStop)
train$NatureOfStop <- gsub("^dangerous driver", "Car Related", train$NatureOfStop)
train$NatureOfStop <- gsub("^Street racing", "Car Related", train$NatureOfStop)
train$NatureOfStop <- gsub("^Traffic", "Car Related", train$NatureOfStop)
train$NatureOfStop <- gsub("^pursuit of a vehicle", "Suspect", train$NatureOfStop)
train$NatureOfStop <- gsub("^[oO]ff.+", "Off Duty", train$NatureOfStop)
train$NatureOfStop <- gsub("^[cC]all [fF]or [sS]ervice", "Call for Service", train$NatureOfStop)
train$NatureOfStop <- gsub("^[eE]mergencey [cC]all [oO]r [rR]equest [fF]or [aA]ssitance", "Call for Service", train$NatureOfStop)          
train$NatureOfStop <- gsub("^[eE]mergency [cC]all [oO]r [rR]equest [fF]or [aA]ssistance", "Call for Service", train$NatureOfStop)       
train$NatureOfStop <- gsub("^911 hang-up", "Call for Service", train$NatureOfStop)
train$NatureOfStop <- gsub("^Radio Call", "Call for Service", train$NatureOfStop)
train$NatureOfStop <- gsub("^Citizen Contact", "Call for Service", train$NatureOfStop)
train$NatureOfStop <- gsub("^CFS/Op-100", "Call for Service", train$NatureOfStop)
train$NatureOfStop <- gsub("^Op 100", "Call for Service", train$NatureOfStop)
train$NatureOfStop <- gsub("^arrest", "Crime", train$NatureOfStop)
train$NatureOfStop <- gsub("^Arrest", "Crime", train$NatureOfStop)
train$NatureOfStop <- gsub("^Foot Chase", "Crime", train$NatureOfStop)
train$NatureOfStop <- gsub("^Alarm activation", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^Expired plates", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^Assist the Officer", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^Eviction", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^Transient", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^pedestrian stop", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^Proactive Policing", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^Public tranportation fees", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^Pedestrian Check", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^Investigation", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^Sexual predator", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^Tampering with vehicle", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^tire slashing", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^Trespassing", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^Vandalism", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^Flagged down", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^Fraud", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^Trespassing", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("^Property crime", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("Property Damage", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub(".+een drinking", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("new year's eve patrol", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("Patrol", "Other", train$NatureOfStop)
train$NatureOfStop <- gsub("Aggravated kidnapping", "Hostage or Major Emergency", train$NatureOfStop)
train$NatureOfStop <- gsub("Carjacking;Sexual Assault;Kidnapping", "Hostage or Major Emergency", train$NatureOfStop)
train$NatureOfStop <- gsub("Hostage situation", "Hostage or Major Emergency", train$NatureOfStop)
train$NatureOfStop <- gsub("Hostage; firearm", "Hostage or Major Emergency", train$NatureOfStop)
train$NatureOfStop <- gsub("Hostage, barricade, or other emergency situation", "Hostage or Major Emergency", train$NatureOfStop)
train$NatureOfStop <- gsub("Domestic violence; hostage", "Hostage or Major Emergency", train$NatureOfStop)
train$NatureOfStop <- gsub("Kidnapping", "Hostage or Major Emergency", train$NatureOfStop)
train$NatureOfStop <- gsub(".+jury to child", "Hostage or Major Emergency", train$NatureOfStop)
train$NatureOfStop <- gsub("SWAT", "Hostage or Major Emergency", train$NatureOfStop)
train$NatureOfStop <- gsub(".+session", "Weapon Possesion", train$NatureOfStop)
train$NatureOfStop <- gsub("Aggrevated Assault; car accident", "Aggrevated Assault", train$NatureOfStop)

summary(factor(train$NatureOfStop))
levels(factor(train$NatureOfStop))

#Cleanining Test for Nature of Stop
test$NatureOfStop <- gsub("^Agg DV Assault", "Aggrevated Assault", test$NatureOfStop)
test$NatureOfStop <- gsub("^Agg-Assault", "Aggrevated Assault", test$NatureOfStop)
test$NatureOfStop <- gsub("^Agg. Assault", "Aggrevated Assault", test$NatureOfStop)
test$NatureOfStop <- gsub("^Attacked officer", "Aggrevated Assault", test$NatureOfStop)
test$NatureOfStop <- gsub("^Agg. Assault", "Aggrevated Assault", test$NatureOfStop)
test$NatureOfStop <- gsub("^Domestic disturbance; assaultling police officer", "Aggrevated Assault", test$NatureOfStop)
test$NatureOfStop <- gsub("^Domestic [vV]iolen.+", "Assault", test$NatureOfStop)
test$NatureOfStop <- gsub("^Ambush", "Assault", test$NatureOfStop)
test$NatureOfStop <- gsub("^Fight / disorderly conduct", "Assault", test$NatureOfStop)
test$NatureOfStop <- gsub("^Medical help; assault", "Assault", test$NatureOfStop)
test$NatureOfStop <- gsub("^Reckless driving; assault on officer", "Assault", test$NatureOfStop)
test$NatureOfStop <- gsub("^Violence; public safety threat", "Assault", test$NatureOfStop)
test$NatureOfStop <- gsub("^[bB]urg.+", "Burglary", test$NatureOfStop)
test$NatureOfStop <- gsub("witness.+", "Crime", test$NatureOfStop)
test$NatureOfStop <- gsub("Threatening officer", "Crime", test$NatureOfStop)
test$NatureOfStop <- gsub("Murder", "Homicide", test$NatureOfStop)
test$NatureOfStop <- gsub("Arrest warrant;attempted murder", "Homicide", test$NatureOfStop)
test$NatureOfStop <- gsub("Domestic dispute, homicide", "Homicide", test$NatureOfStop)
test$NatureOfStop <- gsub("Intruder; homicide threat; home invasion", "Homicide", test$NatureOfStop)
test$NatureOfStop <- gsub("Stabbing", "Homicide", test$NatureOfStop)
test$NatureOfStop <- gsub("^Hosta.+", "Hostage or Major Emergency", test$NatureOfStop)
test$NatureOfStop <- gsub("^Bomb Investigation", "Hostage or Major Emergency", test$NatureOfStop)
test$NatureOfStop <- gsub("^Kidnapping", "Hostage or Major Emergency", test$NatureOfStop)
test$NatureOfStop <- gsub("^[sS]tolen.+", "Larceny", test$NatureOfStop)
test$NatureOfStop <- gsub("^Traffic; stolen car", "Larceny", test$NatureOfStop)
test$NatureOfStop <- gsub("^vehicle theft", "Larceny", test$NatureOfStop)
test$NatureOfStop <- gsub("^theft", "Larceny", test$NatureOfStop)
test$NatureOfStop <- gsub("^Suspected carjacking", "Larceny", test$NatureOfStop)
test$NatureOfStop <- gsub("^[dD]ru.+", "Narcotics", test$NatureOfStop)
test$NatureOfStop <- gsub("^[nN]arc.+", "Narcotics", test$NatureOfStop)
test$NatureOfStop <- gsub("^Complaint; drugs", "Narcotics", test$NatureOfStop)
test$NatureOfStop <- gsub("^Search warrant- Drugs", "Narcotics", test$NatureOfStop)
test$NatureOfStop <- gsub("^Off-duty", "Off Duty", test$NatureOfStop)
test$NatureOfStop <- gsub("^Off duty", "Off Duty", test$NatureOfStop)
test$NatureOfStop <- gsub("^Eviction", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Alarm call", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Check welfare; fire", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Counterfeiting", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Asst. Officer", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Asst. Officer", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Investigat.+", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^other$", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Park rules", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Patr.+", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^person being threatened", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Property destruction", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Restricted area; trespassing at police station", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^prostitution solicitation", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Prowlers", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Publi.+", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^runaway", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Self-Initiated", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Sex crime", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Sexual harassment", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Trespassing", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Underaged party", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^Welfare check", "Other", test$NatureOfStop)
test$NatureOfStop <- gsub("^[aA]ggravated robbery", "Robbery", test$NatureOfStop)
test$NatureOfStop <- gsub("^[rR]obb.+", "Robbery", test$NatureOfStop)
test$NatureOfStop <- gsub("^[aA]rmed [rR]obbery", "Robbery", test$NatureOfStop)
test$NatureOfStop <- gsub("^Home inv.+", "Robbery", test$NatureOfStop)
test$NatureOfStop <- gsub("^Party Wanted-Robbery", "Robbery", test$NatureOfStop)
test$NatureOfStop <- gsub("^Shot.+", "Shots Fired", test$NatureOfStop)
test$NatureOfStop <- gsub("^[sS]hoo.+", "Shots Fired", test$NatureOfStop)
test$NatureOfStop <- gsub("^Weapons posession; shooting", "Shots Fired", test$NatureOfStop)
test$NatureOfStop <- gsub("^accidental fire", "Shots Fired", test$NatureOfStop)
test$NatureOfStop <- gsub("^Active shooter", "Shots Fired", test$NatureOfStop)
test$NatureOfStop <- gsub("^Assault on officer; shooting; mental health", "Shots Fired", test$NatureOfStop)
test$NatureOfStop <- gsub("^Officer shot", "Shots Fired", test$NatureOfStop)
test$NatureOfStop <- gsub("^BO.+", "Suspect", test$NatureOfStop)
test$NatureOfStop <- gsub("^gang sweeps", "Suspect", test$NatureOfStop)
test$NatureOfStop <- gsub("^Police chase", "Suspect", test$NatureOfStop)
test$NatureOfStop <- gsub("^Vehicle Pursuit", "Suspect", test$NatureOfStop)
test$NatureOfStop <- gsub("^vehicle chase", "Suspect", test$NatureOfStop)
test$NatureOfStop <- gsub("^Fleeing vehicle", "Suspect", test$NatureOfStop)
test$NatureOfStop <- gsub("^[sS]uspi.+", "Suspicious Entity", test$NatureOfStop)
test$NatureOfStop <- gsub("^Pursuit", "Suspicious Entity", test$NatureOfStop)
test$NatureOfStop <- gsub("^Ran from officers", "Suspicious Entity", test$NatureOfStop)
test$NatureOfStop <- gsub("^Execution of a warrant", "Warrant", test$NatureOfStop)
test$NatureOfStop <- gsub("^Traffic stop; warrant", "Warrant", test$NatureOfStop)
test$NatureOfStop <- gsub("^Search.+", "Warrant", test$NatureOfStop)
test$NatureOfStop <- gsub("^Search.+", "Warrant", test$NatureOfStop)
test$NatureOfStop <- gsub("^Warrants$", "Warrant", test$NatureOfStop)
test$NatureOfStop <- gsub("^warrant$", "Warrant", test$NatureOfStop)
test$NatureOfStop <- gsub("^Warrant/crime bulletin; marijuana", "Warrant", test$NatureOfStop)
test$NatureOfStop <- gsub("^[wW]eap.+", "Weapon Possesion", test$NatureOfStop)
test$NatureOfStop <- gsub("^[fF]ire.+", "Weapon Possesion", test$NatureOfStop)
test$NatureOfStop <- gsub("^Mental Health; weapons posession", "Weapon Possesion", test$NatureOfStop)
test$NatureOfStop <- gsub("^[aA]rm.+", "Weapon Possesion", test$NatureOfStop)
test$NatureOfStop <- gsub("^Disturbance; threatened shooting", "Weapon Possesion", test$NatureOfStop)
test$NatureOfStop <- gsub("^Domestic disturbance; firearm", "Weapon Possesion", test$NatureOfStop)
test$NatureOfStop <- gsub("^Gun posession", "Weapon Possesion", test$NatureOfStop)
test$NatureOfStop <- gsub("^Man with a gun", "Weapon Possesion", test$NatureOfStop)
test$NatureOfStop <- gsub("^Gang activity; weapon posession; suspicious subject", "Weapon Possesion", test$NatureOfStop)
test$NatureOfStop <- gsub("^Nightlife; gun posession", "Weapon Possesion", test$NatureOfStop)
test$NatureOfStop <- gsub("^Sus Party Armed", "Weapon Possesion", test$NatureOfStop)
test$NatureOfStop <- gsub("^showed firearm to bus riders", "Weapon Possesion", test$NatureOfStop)
test$NatureOfStop <- gsub("^[sS]uici.+", "Mental Health", test$NatureOfStop)
test$NatureOfStop <- gsub("^[mM]ent.+", "Mental Health", test$NatureOfStop)
test$NatureOfStop <- gsub("^Domestic dispute; mental health; suicide", "Mental Health", test$NatureOfStop)
test$NatureOfStop <- gsub("^Major disturbance; mental illness", "Mental Health", test$NatureOfStop)
test$NatureOfStop <- gsub("^threatening behavior; mental illness", "Mental Health", test$NatureOfStop)
test$NatureOfStop <- gsub("^[cC]all [fF]or [sS]ervice", "Call for Service", test$NatureOfStop)
test$NatureOfStop <- gsub("^Citizen Contact", "Call for Service", test$NatureOfStop)
test$NatureOfStop <- gsub("^Emergency Call or Request for Assistance", "Call for Service", test$NatureOfStop)
test$NatureOfStop <- gsub("^Radio Call", "Call for Service", test$NatureOfStop)
test$NatureOfStop <- gsub("^[tT]raff.+", "Car Related", test$NatureOfStop)
test$NatureOfStop <- gsub("^[cC]ar\\s.+", "Car Related", test$NatureOfStop)
test$NatureOfStop <- gsub("^Street racing", "Car Related", test$NatureOfStop)
test$NatureOfStop <- gsub("^vehicle drove toward cop car", "Car Related", test$NatureOfStop)
test$NatureOfStop <- gsub("^Vehicle [sS]top", "Car Related", test$NatureOfStop)
test$NatureOfStop <- gsub("^Ftraffic stop", "Car Related", test$NatureOfStop)
test$NatureOfStop <- gsub("^[dD]omes.+", "Disturbance", test$NatureOfStop)
test$NatureOfStop <- gsub("^argument", "Disturbance", test$NatureOfStop)
test$NatureOfStop <- gsub("^Family Disturbance", "Disturbance", test$NatureOfStop)
test$NatureOfStop <- gsub("^Major disturbance$", "Disturbance", test$NatureOfStop)
test$NatureOfStop <- gsub("^Noise complaint", "Disturbance", test$NatureOfStop)
test$NatureOfStop <- gsub("[uU]nkn.+", NA, test$NatureOfStop) 
test$NatureOfStop <- gsub("N/A", NA, test$NatureOfStop)            

summary(factor(test$NatureOfStop))
levels(factor(test$NatureOfStop))
```